// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const env = typeof import.meta.env !== 'undefined' ? import.meta.env : process.env;
const SUPABASE_URL = env.VITE_SUPABASE_URL || "https://mock.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = env.VITE_SUPABASE_ANON_KEY || "mock_key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: typeof window !== 'undefined',
      storage: typeof window !== 'undefined' ? localStorage : undefined as any,
    }
  }
);